import { Result } from '../../../domain/shared/Result';
import { FinancialCategory } from '../../../domain/finance/entities/FinancialCategory';
import { IFinancialCategoryRepository } from '../../../domain/finance/repositories';
import { IUseCase } from '../../shared/types/IUseCase';
import { CreateFinancialCategoryInputDTO, FinancialCategoryResponseDTO } from '../dtos/FinanceDTOs';
import { FinancialCategoryMapper } from '../mappers/FinancialCategoryMapper';

export class CreateFinancialCategory implements IUseCase<CreateFinancialCategoryInputDTO, FinancialCategoryResponseDTO> {
  constructor(
    private readonly categoryRepository: IFinancialCategoryRepository,
  ) {}

  async execute(input: CreateFinancialCategoryInputDTO): Promise<Result<FinancialCategoryResponseDTO>> {
    try {
      // Validate code uniqueness
      const existingByCode = await this.categoryRepository.findByCode(input.code);
      if (existingByCode) {
        return Result.fail<FinancialCategoryResponseDTO>('A category with this code already exists');
      }

      // Validate parent exists if provided
      let level = 0;
      if (input.parentId !== undefined) {
        const parent = await this.categoryRepository.findById(input.parentId);
        if (!parent) {
          return Result.fail<FinancialCategoryResponseDTO>('Parent category not found');
        }
        level = (parent.level ?? 0) + 1;
      }

      const category = FinancialCategory.create({
        id: 0, // Auto-generated by persistence layer
        code: input.code,
        name: input.name,
        type: input.type,
        parentId: input.parentId,
        level,
        description: input.description,
        active: true,
      });

      const saved = await this.categoryRepository.create(category);
      return Result.ok<FinancialCategoryResponseDTO>(FinancialCategoryMapper.toDTO(saved));
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unexpected error creating financial category';
      return Result.fail<FinancialCategoryResponseDTO>(message);
    }
  }
}
