export {
  RegisterEventInputDTO,
  RegisterEventBirthInputDTO,
  RegisterEventDeathInputDTO,
  RegisterEventHealthInputDTO,
  RegisterEventMovementInputDTO,
  RegisterEventWeighingInputDTO,
  RegisterEventReproductionInputDTO,
  RegisterEventSaleInputDTO,
  RegisterEventPurchaseInputDTO,
  RegisterEventWeaningInputDTO,
  RegisterEventIdentificationInputDTO,
  EventResponseDTO,
  EventBirthResponseDTO,
  EventWeighingResponseDTO,
  EventReproductionResponseDTO,
  EventFiltersInputDTO,
  ADGCalculationResponseDTO,
  EstimatedBirthDateResponseDTO,
} from './EventDTOs';
